"""Initial schema with evaluations and benchmarks tables

Revision ID: 8312ef6ff4bf
Revises:
Create Date: 2025-09-19 09:02:56.264780

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8312ef6ff4bf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("preprocessed_benchmark_id", sa.UUID(), nullable=False),
        sa.Column("agent_config_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("results_json", sa.Text(), nullable=True),
        sa.Column("failure_reason_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("evaluation_id", name=op.f("pk_evaluations")),
    )
    op.create_table(
        "preprocessed_benchmarks",
        sa.Column("benchmark_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("format_version", sa.String(length=50), nullable=False),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("questions_json", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            "benchmark_id", name=op.f("pk_preprocessed_benchmarks")
        ),
        sa.UniqueConstraint("name", name=op.f("uq_preprocessed_benchmarks_name")),
    )

    # Create performance indexes
    op.create_index("ix_evaluations_status", "evaluations", ["status"])
    op.create_index(
        "ix_evaluations_benchmark_id", "evaluations", ["preprocessed_benchmark_id"]
    )
    op.create_index("ix_evaluations_created_at", "evaluations", ["created_at"])
    op.create_index(
        "ix_benchmarks_format_version", "preprocessed_benchmarks", ["format_version"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index("ix_benchmarks_format_version", table_name="preprocessed_benchmarks")
    op.drop_index("ix_evaluations_created_at", table_name="evaluations")
    op.drop_index("ix_evaluations_benchmark_id", table_name="evaluations")
    op.drop_index("ix_evaluations_status", table_name="evaluations")

    # Then drop tables
    op.drop_table("preprocessed_benchmarks")
    op.drop_table("evaluations")
    # ### end Alembic commands ###
